### ISSUE TITLE
[BUG] thread 'main' panicked at 'no group named 'owner''

### ISSUE THREAD

**Issue by donovanglover** [hyprland-community/hyprland-autoname-workspaces#82] opened 2023-06-14 13:23 UTC
**Describe the bug**
Crashes when switching to a workspace with [osu!lazer](https://search.nixos.org/packages?show=osu-lazer-bin)

**Program version?**

- Crashes in both 1.0.0 and the latest commit on main

**Program configuration dump? (ideally)**

- Crashes with the default config

**To Reproduce**

1. Start `hyprland-autoname-workspaces`
2. Start osu!
3. Change workspaces and observe crash

**Expected behavior**
No crash

**Linux Distro (please complete the following information):**

- NixOS

**Additional context**
```
thread 'main' panicked at 'no group named 'owner'', /build/hyprland-autoname-workspaces-1.0.0-vendor.tar.gz/regex/src/re_unicode.rs:1172:32
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <regex::re_unicode::Captures as core::ops::index::Index<&str>>::index
   3: hyprland::event_listener::shared::event_parser
   4: hyprland::event_listener::mutable::EventListener::start_listener
   5: hyprland_autoname_workspaces::renamer::Renamer::start_listeners
   6: hyprland_autoname_workspaces::main
```

**Comment by cyrinux** [comment] 2023-06-14 15:56
Can you please share you config using - -dump flag?

**Comment by cyrinux** [comment] 2023-06-14 16:14
Can you also be sure to use the last hyprland from main/master ?

**Comment by donovanglover** [comment] 2023-06-19 21:40
Here's `hyprctl clients -j`. I'm using hyprland v0.26.0.

```json
{
    "address": "0x3e00260",
    "mapped": true,
    "hidden": false,
    "at": [0, 0],
    "size": [1875, 1080],
    "workspace": {
        "id": 4,
        "name": "<b><span color='red'>4-four:</span></b> "
    },
    "floating": false,
    "monitor": 0,
    "class": "osu!",
    "title": "osu!",
    "initialClass": "osu!",
    "initialTitle": "osu!",
    "pid": 385205,
    "xwayland": true,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
}
```

I assume this is related to the class/title ending with an exclamation point. osu! isn't the only program to cause this error, but it is the easiest to reproduce with.

**Comment by cyrinux** [comment] 2023-06-19 21:53
Thx, I I'll dig more with those infos 👍

**Comment by cyrinux** [comment] 2023-07-03 21:05
@donovanglover do you reproduce the bug with last version of hyprland and autoname ?

**Comment by donovanglover** [comment] 2023-07-03 21:33
Unfortunately still crashes with the same error.

```fish
thread 'main' panicked at 'no group named 'owner'', /build/hyprland-autoname-workspaces-1.1.1-vendor.tar.gz/regex/src/re_unicode.rs:1172:32
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <regex::re_unicode::Captures as core::ops::index::Index<&str>>::index
   3: hyprland::event_listener::shared::event_parser
   4: hyprland::event_listener::mutable::EventListener::start_listener
   5: hyprland_autoname_workspaces::renamer::Renamer::start_listeners
   6: hyprland_autoname_workspaces::main
```

**Comment by cyrinux** [comment] 2023-07-08 08:49
@donovanglover I try to replicate with unit test and also just running kitty in X11 mode with `KITTY_DISABLE_WAYLAND=1 kitty --class 'osu!test' --title 'osu!test` but I cant reproduce.

Do you have another idea about what can be special in your setup ? Do you still reproduce with last version or hyrpland from git and autoname from git and default config ?

**Comment by donovanglover** [comment] 2023-07-08 14:14
Wasn't able to reproduce it with kitty or a binary that ended in `!`. The `osu!` executable is a script that calls a script that starts an app image. Still reproducible in v1.1.3, although now the [line number](https://github.com/rust-lang/regex/blob/1.9.1/src/regex/string.rs#L2007) is different. [`ironbar`](https://github.com/JakeStanger/ironbar/issues/225) had a similar issue but didn't crash, so I feel like this is an issue with [hyprland-rs](https://github.com/hyprland-community/hyprland-rs/blob/861f506f3e762aa6b49ca17e808fc14cb9d6eadb/src/event_listener/shared.rs#L693).

**Comment by Anomalocaridid** [comment] 2023-07-08 19:45
I have the same problem with Minecraft. It seems like it only happens when I move to another workspace while it's in fullscreen, though. If I close it or exit fullscreen without moving workspaces it seems like the error does not appear.

Also, Minecraft has periods in its title and class, which might be related to osu!lazer having an exclamation mark in its title and class. In addition, I noticed that the backtrace mentions regex, which might somehow be related to special characters causing issues.

version: `hyprland-autoname-workspaces 1.1.3`

backtrace:
```
thread 'main' panicked at 'no group named 'owner'', /build/hyprland-autoname-workspaces-1.1.3-vendor.tar.gz/regex/src/regex/string.rs:2007:32
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <regex::regex::string::Captures as core::ops::index::Index<&str>>::index
   3: hyprland::event_listener::shared::event_parser
   4: hyprland::event_listener::mutable::EventListener::start_listener
   5: hyprland_autoname_workspaces::renamer::Renamer::start_listeners
   6: hyprland_autoname_workspaces::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

`hyprctl clients -j`:
``` json
[{
    "address": "0x20f59e0",
    "mapped": true,
    "hidden": false,
    "at": [22, 60],
    "size": [1316, 686],
    "workspace": {
        "id": 2,
        "name": "2: <span color='#00FF00'></span>"
    },
    "floating": false,
    "monitor": 0,
    "class": "org.wezfurlong.wezterm",
    "title": "~/nixos",
    "initialClass": "org.wezfurlong.wezterm",
    "initialTitle": "wezterm",
    "pid": 4023,
    "xwayland": false,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
},{
    "address": "0x2090100",
    "mapped": false,
    "hidden": false,
    "at": [0, 0],
    "size": [0, 0],
    "workspace": {
        "id": -1,
        "name": ""
    },
    "floating": false,
    "monitor": -1,
    "class": "",
    "title": "",
    "initialClass": "",
    "initialTitle": "",
    "pid": 0,
    "xwayland": true,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
},{
    "address": "0x2091560",
    "mapped": false,
    "hidden": false,
    "at": [0, 0],
    "size": [0, 0],
    "workspace": {
        "id": -1,
        "name": ""
    },
    "floating": false,
    "monitor": -1,
    "class": "",
    "title": "",
    "initialClass": "",
    "initialTitle": "",
    "pid": 0,
    "xwayland": true,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
},{
    "address": "0x20929c0",
    "mapped": false,
    "hidden": false,
    "at": [0, 0],
    "size": [0, 0],
    "workspace": {
        "id": -1,
        "name": ""
    },
    "floating": false,
    "monitor": -1,
    "class": "",
    "title": "",
    "initialClass": "",
    "initialTitle": "",
    "pid": 0,
    "xwayland": true,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
},{
    "address": "0x2093e20",
    "mapped": false,
    "hidden": false,
    "at": [0, 0],
    "size": [0, 0],
    "workspace": {
        "id": -1,
        "name": ""
    },
    "floating": false,
    "monitor": -1,
    "class": "",
    "title": "",
    "initialClass": "",
    "initialTitle": "",
    "pid": 0,
    "xwayland": true,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
},{
    "address": "0x2095280",
    "mapped": true,
    "hidden": false,
    "at": [22, 60],
    "size": [1316, 686],
    "workspace": {
        "id": 1,
        "name": "1: 󰍳 󰍳"
    },
    "floating": false,
    "monitor": 0,
    "class": "org.prismlauncher.PrismLauncher",
    "title": "Prism Launcher 7.1",
    "initialClass": "org.prismlauncher.PrismLauncher",
    "initialTitle": "Prism Launcher 7.1",
    "pid": 14979,
    "xwayland": false,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
},{
    "address": "0x20cbaa0",
    "mapped": false,
    "hidden": false,
    "at": [0, 0],
    "size": [0, 0],
    "workspace": {
        "id": -1,
        "name": ""
    },
    "floating": false,
    "monitor": -1,
    "class": "",
    "title": "",
    "initialClass": "",
    "initialTitle": "",
    "pid": 0,
    "xwayland": true,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
},{
    "address": "0x21d2780",
    "mapped": true,
    "hidden": false,
    "at": [0, 0],
    "size": [1360, 768],
    "workspace": {
        "id": 1,
        "name": "1: 󰍳 󰍳"
    },
    "floating": true,
    "monitor": 0,
    "class": "Minecraft 1.20.1",
    "title": "Minecraft 1.20.1",
    "initialClass": "Minecraft 1.20.1",
    "initialTitle": "Minecraft 1.20.1",
    "pid": 57413,
    "xwayland": true,
    "pinned": false,
    "fullscreen": true,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
}]
```

**Comment by cyrinux** [comment] 2023-07-08 20:47
Can you please run from the source with `cargo r --profile dev` I would like to see if you receive an error with a not handled event.

**Comment by cyrinux** [comment] 2023-07-08 21:31
Ok, I feel like we found the issue, I should be fix soon in hyprland-rs, I will do release then for both projects.

**Comment by Anomalocaridid** [comment] 2023-07-08 22:14
After running the latest commit to main with `cargo run`, it looks like it's fixed on my end. Thank you!

**Comment by cyrinux** [comment] 2023-07-08 23:41
Will do a release now.

**Closed by cyrinux** 2023-07-08 23:41 UTC
Labels: bug, help wanted, question

**Comment by donovanglover** [comment] 2023-07-09 00:42
Fixed for me as well. Thanks!
